version: '3.7'

services:
  web:
    build: 
      context: ./web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data: 