version: '3.4'

services:
  web:
    restart: always
    # container_name: mainapp
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    # command: python manage.py runserver 0.0.0.0:8000 # command buat ngejalanin server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 #load Gunicorn server
    # volumes:
    #   - ./HostApp/:/usr/src/web/ # share project local
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    restart: always
    # container_name: dbapp
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    
volumes:
  postgres_data: 