version: '3.7'

services:
  web:
    build: 
      context: ./web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    # restart: always
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    
volumes:
  postgres_data: 