version: '3.7'

services:
  web:
    restart: always
    volumes:
      - ./web/HostApp/:/usr/src/web/ # share project local
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    restart: always
    # container_name: dbapp
    env_file:
      - ./.env.dev.db
    