version: '3.7'

services:
  web:
    restart: always
    # container_name: mainapp
    build: 
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose: 
      - 8000
    env_file:
      - ./.env.prod
      
  db:
    restart: always
    # container_name: dbapp
    env_file:
      - ./.env.prod.db
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    # restart: always
    depends_on:
      - web
    
volumes:
  postgres_data: 
  static_volume:
  media_volume: